<?php
use IGBZ\Suite\Support\Admin\SettingsPage;
use IGBZ\Suite\Support\Schema;
use IGBZ\Suite\Support\Settings;

/**
 * Phase 04 drift guard: numbers and pairings the completion plan tracks must not silently
 * diverge from the code. Anything this test pins has a matching entry in
 * PHASE-01-INVENTORY.json (regenerated by `_devenv/phase01_inventory.py`); changing one side
 * without the other turns the suite red here or in the `_devenv/test.sh` drift step.
 */
final class DriftGuardTest extends TestCase {

	/** Registry members that are generated tokens, not admin-form password fields. */
	private const REGISTRY_WITHOUT_FIELD = [
		'pado.api_key', // rendered on the Pado page, not the shared settings form
		'vip.media_hmac_secret', // generated token, no form field
	];

	/**
	 * admin-ajax actions reachable without a WordPress login. Each one must carry its own
	 * rate limit / nonce; adding a new anonymous action must be a deliberate, reviewed change.
	 */
	private const ANONYMOUS_AJAX_ALLOWLIST = [ 'igbz_otp' ];

	public function run(): void {
		$this->table_count_is_pinned();
		$this->db_version_is_pinned();
		$this->every_password_field_is_a_registered_secret();
		$this->every_registered_secret_has_a_field_or_is_generated();
		$this->capability_matrix_is_pinned();
		$this->anonymous_ajax_surface_is_pinned();
	}

	/** Phase 06: the capability matrix is part of the trust boundary; drift must be loud. */
	private function capability_matrix_is_pinned(): void {
		$this->assert_same(
			11,
			count( \IGBZ\Suite\Support\Capabilities::all() ),
			'Capability matrix drifted from the pinned 11 members (PHASE-01-INVENTORY.json access_control)'
		);
	}

	/** Phase 06: no new anonymous admin-ajax action may appear without review. */
	private function anonymous_ajax_surface_is_pinned(): void {
		$found = [];
		$root  = __DIR__ . '/../src';
		$it    = new \RecursiveIteratorIterator(
			new \RecursiveDirectoryIterator( $root, \FilesystemIterator::SKIP_DOTS )
		);
		foreach ( $it as $file ) {
			if ( 'php' !== $file->getExtension() ) {
				continue;
			}
			if ( preg_match_all( "/wp_ajax_nopriv_([A-Za-z0-9_]+)/", (string) file_get_contents( $file->getPathname() ), $matches ) ) {
				$found = array_merge( $found, $matches[1] );
			}
		}
		sort( $found );
		$this->assert_same(
			self::ANONYMOUS_AJAX_ALLOWLIST,
			$found,
			'Anonymous admin-ajax surface changed; every anonymous action needs its own rate limit and review'
		);
	}

	private function table_count_is_pinned(): void {
		$this->assert_same(
			95,
			count( Schema::statements() ),
			'Schema table count drifted from the pinned baseline (95 / PHASE-01-INVENTORY.json database.table_count)'
		);
	}

	private function db_version_is_pinned(): void {
		// Read from the plugin bootstrap file, not the constant: the test harness never loads
		// igbz-suite.php, and parsing the source of truth keeps this check honest.
		$source = (string) file_get_contents( __DIR__ . '/../igbz-suite.php' );
		$found  = preg_match( "/define\(\s*'IGBZ_DB_VERSION',\s*(\d+)/", $source, $matches );
		$this->assert_same( 1, $found, 'IGBZ_DB_VERSION define not found in igbz-suite.php' );
		$this->assert_same(
			44,
			(int) ( $matches[1] ?? 0 ),
			'IGBZ_DB_VERSION drifted from the pinned baseline (44 / PHASE-01-INVENTORY.json database.version)'
		);
	}

	/** @return array<string, array<string,mixed>> key => field definition */
	private function password_fields(): array {
		// Tabs are filtered by active modules, so the guard only sees every password field when
		// every module is switched on. Restore the previous selection afterwards.
		$before = \IGBZ\Suite\Support\Modules::enabled_list();
		\IGBZ\Suite\Support\Modules::save( \IGBZ\Suite\Support\Modules::all() );

		$page   = new SettingsPage( new Settings() );
		$fields = [];
		foreach ( array_keys( $page->tabs() ) as $tab ) {
			foreach ( $page->fields( (string) $tab ) as $field ) {
				if ( 'password' === ( $field['type'] ?? '' ) && isset( $field['key'] ) ) {
					$fields[ (string) $field['key'] ] = $field;
				}
			}
		}

		\IGBZ\Suite\Support\Modules::save( $before );
		return $fields;
	}

	private function every_password_field_is_a_registered_secret(): void {
		$settings = new Settings();
		foreach ( array_keys( $this->password_fields() ) as $key ) {
			$this->assert_true(
				$settings->is_secret( $key ),
				sprintf(
					'Settings password field "%s" is not in Settings::SECRETS - it would be stored and re-rendered in plaintext',
					$key
				)
			);
		}
	}

	private function every_registered_secret_has_a_field_or_is_generated(): void {
		$fields = $this->password_fields();
		foreach ( Settings::secret_keys() as $key ) {
			$known = isset( $fields[ $key ] ) || in_array( $key, self::REGISTRY_WITHOUT_FIELD, true );
			$this->assert_true(
				$known,
				sprintf(
					'Registry secret "%s" has no settings form field and is not on the generated-token allow-list',
					$key
				)
			);
		}
	}
}
